hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("~/.config/hypr/waybar/run")
    hl.exec_cmd("~/.config/hypr/bin/notif")
    hl.exec_cmd("dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY")
    hl.exec_cmd("lxsession")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
end)
